# Generated by Django 5.1.4 on 2026-06-15 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisionTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "interval_days",
                    models.IntegerField(default=1, help_text="Days until next review"),
                ),
                (
                    "easiness_factor",
                    models.FloatField(default=2.5, help_text="SM-2 EF, min 1.3"),
                ),
                (
                    "repetitions",
                    models.IntegerField(
                        default=0, help_text="Consecutive correct recalls"
                    ),
                ),
                (
                    "quality_score",
                    models.IntegerField(default=0, help_text="Last quality score 0-5"),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("due", "Due"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                            ("upcoming", "Upcoming"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_reviews", models.IntegerField(default=0)),
                ("review_dates", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_tasks",
                        to="curriculum.chapter",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_tasks",
                        to="curriculum.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revision_tasks",
                        to="curriculum.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Revision Task",
                "ordering": ["due_date"],
            },
        ),
    ]
