# Generated by Django 5.1.4 on 2026-06-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="preferred_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("ml", "Malayalam"),
                    ("manglish", "Manglish"),
                ],
                default="en",
                max_length=20,
            ),
        ),
    ]
