# Generated by Django 5.1.4 on 2026-06-15 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MockQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_image",
                    models.ImageField(blank=True, upload_to="assessment/questions/"),
                ),
                (
                    "options",
                    models.JSONField(
                        help_text='{"A": "...", "B": "...", "C": "...", "D": "..."}'
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(help_text="A, B, C, or D", max_length=1),
                ),
                ("explanation", models.TextField(blank=True)),
                ("marks", models.IntegerField(default=1)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.chapter",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mock Question",
                "ordering": ["test", "order"],
            },
        ),
        migrations.CreateModel(
            name="MockResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("total_marks", models.IntegerField(default=0)),
                ("correct_count", models.IntegerField(default=0)),
                ("incorrect_count", models.IntegerField(default=0)),
                ("unanswered_count", models.IntegerField(default=0)),
                ("accuracy_percentage", models.FloatField(default=0.0)),
                ("time_taken_minutes", models.IntegerField(default=0)),
                (
                    "analysis_json",
                    models.JSONField(
                        blank=True, default=dict, help_text="Detailed score breakdown"
                    ),
                ),
                ("weak_areas", models.JSONField(blank=True, default=list)),
                ("strong_areas", models.JSONField(blank=True, default=list)),
                ("improvement_plan", models.TextField(blank=True)),
                ("ai_feedback", models.TextField(blank=True)),
                (
                    "readiness_impact",
                    models.FloatField(
                        default=0.0, help_text="Impact on readiness score"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mock Result",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="MCQAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField(blank=True)),
                ("options", models.JSONField(blank=True, default=dict)),
                ("correct_answer", models.CharField(blank=True, max_length=1)),
                ("selected_answer", models.CharField(blank=True, max_length=1)),
                ("is_correct", models.BooleanField(default=False)),
                ("time_taken_seconds", models.IntegerField(default=0)),
                ("explanation", models.TextField(blank=True)),
                ("difficulty", models.CharField(default="medium", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.chapter",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcq_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="assessment.mockquestion",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="assessment.mockresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCQ Attempt",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MockTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("subject", "Subject Test"),
                            ("full", "Full Syllabus Test"),
                            ("chapter", "Chapter Test"),
                            ("quick", "Quick Test"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_minutes", models.IntegerField(default=60)),
                ("total_marks", models.IntegerField(default=100)),
                ("total_questions", models.IntegerField(default=30)),
                ("passing_marks", models.IntegerField(default=40)),
                ("negative_marking", models.BooleanField(default=True)),
                ("negative_mark_value", models.FloatField(default=0.25)),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("difficulty_level", models.CharField(default="medium", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mock_tests",
                        to="curriculum.chapter",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mock_tests",
                        to="curriculum.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mock Test",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mockresult",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="assessment.mocktest",
            ),
        ),
        migrations.AddField(
            model_name="mockquestion",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessment.mocktest",
            ),
        ),
    ]
