# Generated by Django 5.1.4 on 2026-06-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name for frontend", max_length=50
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366f1", help_text="Hex color code", max_length=7
                    ),
                ),
                ("total_weightage", models.IntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "weightage",
                    models.IntegerField(default=0, help_text="Exam weightage (marks)"),
                ),
                (
                    "estimated_hours",
                    models.FloatField(default=5.0, help_text="Estimated study hours"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="curriculum.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chapter",
                "verbose_name_plural": "Chapters",
                "ordering": ["subject", "order"],
                "unique_together": {("subject", "order")},
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "importance_score",
                    models.IntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Medium"),
                            (3, "High"),
                            (4, "Very High"),
                            (5, "Critical"),
                        ],
                        default=3,
                    ),
                ),
                ("estimated_minutes", models.IntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "frequency_in_exams",
                    models.IntegerField(
                        default=0, help_text="How many times appeared in exams"
                    ),
                ),
                ("last_appeared_year", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="curriculum.chapter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
                "ordering": ["chapter", "order"],
            },
        ),
    ]
