# Generated by Django 5.1.4 on 2026-06-15 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consistency_score", models.FloatField(default=50.0)),
                ("discipline_score", models.FloatField(default=50.0)),
                ("motivation_score", models.FloatField(default=50.0)),
                (
                    "procrastination_patterns",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "productive_hours",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Hours when student is most productive",
                    ),
                ),
                ("study_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("total_study_hours", models.FloatField(default=0.0)),
                ("average_daily_hours", models.FloatField(default=0.0)),
                ("missed_days", models.IntegerField(default=0)),
                ("behavior_notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Behavior Profile",
            },
        ),
        migrations.CreateModel(
            name="LearningPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learning_style",
                    models.CharField(
                        choices=[
                            ("visual", "Visual"),
                            ("auditory", "Auditory"),
                            ("reading", "Reading/Writing"),
                            ("kinesthetic", "Kinesthetic"),
                            ("mixed", "Mixed"),
                        ],
                        default="mixed",
                        max_length=20,
                    ),
                ),
                (
                    "explanation_style",
                    models.CharField(
                        choices=[
                            ("simple", "Simple & Short"),
                            ("detailed", "Detailed & Thorough"),
                            ("story", "Story-Based"),
                            ("example", "Example-Heavy"),
                            ("analogy", "Analogy-Based"),
                            ("exam_focused", "Exam-Focused"),
                        ],
                        default="simple",
                        max_length=20,
                    ),
                ),
                ("attention_span_minutes", models.IntegerField(default=30)),
                (
                    "understanding_speed",
                    models.FloatField(default=0.5, help_text="0=slow, 1=fast"),
                ),
                (
                    "favorite_examples",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Types of examples that work well",
                    ),
                ),
                (
                    "preferred_difficulty",
                    models.FloatField(default=0.5, help_text="0=easy, 1=hard"),
                ),
                (
                    "responds_well_to",
                    models.JSONField(
                        blank=True, default=list, help_text="Teaching methods that work"
                    ),
                ),
                (
                    "responds_poorly_to",
                    models.JSONField(
                        blank=True, default=list, help_text="Teaching methods that fail"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="AI observations about learning patterns"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Preference",
            },
        ),
        migrations.CreateModel(
            name="MemorySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("summary_text", models.TextField()),
                ("key_insights", models.JSONField(blank=True, default=list)),
                ("topics_covered", models.JSONField(blank=True, default=list)),
                ("performance_data", models.JSONField(blank=True, default=dict)),
                ("token_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Memory Summary",
                "verbose_name_plural": "Memory Summaries",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="MistakeMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mistake_type",
                    models.CharField(
                        choices=[
                            ("conceptual", "Conceptual Mistake"),
                            ("repeated", "Repeated Error"),
                            ("careless", "Careless Mistake"),
                            ("application", "Application Error"),
                            ("calculation", "Calculation Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question_text", models.TextField()),
                ("student_answer", models.TextField()),
                ("correct_answer", models.TextField()),
                ("explanation", models.TextField(blank=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("occurrences", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mistakes",
                        to="curriculum.chapter",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mistakes",
                        to="curriculum.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mistakes",
                        to="curriculum.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mistake_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mistake Memory",
                "verbose_name_plural": "Mistake Memories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RevisionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quality_score",
                    models.IntegerField(
                        default=3, help_text="0-5, SM-2 quality rating"
                    ),
                ),
                ("time_spent_minutes", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curriculum.chapter",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curriculum.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Revision History",
                "verbose_name_plural": "Revision Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChapterMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "understanding_score",
                    models.FloatField(default=0.0, help_text="0-100"),
                ),
                ("revision_count", models.IntegerField(default=0)),
                (
                    "forgetting_risk",
                    models.FloatField(
                        default=0.0, help_text="0-100, higher = more likely to forget"
                    ),
                ),
                ("completion_percentage", models.FloatField(default=0.0)),
                ("last_studied", models.DateTimeField(blank=True, null=True)),
                ("last_revised", models.DateTimeField(blank=True, null=True)),
                ("total_time_spent", models.FloatField(default=0.0, help_text="Hours")),
                ("ai_notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_memories",
                        to="curriculum.chapter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chapter Memory",
                "verbose_name_plural": "Chapter Memories",
                "unique_together": {("user", "chapter")},
            },
        ),
        migrations.CreateModel(
            name="ConceptMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accuracy", models.FloatField(default=0.0, help_text="0-100")),
                ("total_attempts", models.IntegerField(default=0)),
                ("correct_attempts", models.IntegerField(default=0)),
                ("mistakes_count", models.IntegerField(default=0)),
                ("retention_score", models.FloatField(default=0.0, help_text="0-100")),
                ("last_reviewed", models.DateTimeField(blank=True, null=True)),
                ("review_history", models.JSONField(blank=True, default=list)),
                ("ai_notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_memories",
                        to="curriculum.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Concept Memory",
                "verbose_name_plural": "Concept Memories",
                "unique_together": {("user", "topic")},
            },
        ),
        migrations.CreateModel(
            name="SubjectMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strength_score", models.FloatField(default=50.0, help_text="0-100")),
                ("weakness_score", models.FloatField(default=50.0, help_text="0-100")),
                (
                    "confidence_score",
                    models.FloatField(default=50.0, help_text="0-100"),
                ),
                ("total_time_spent", models.FloatField(default=0.0, help_text="Hours")),
                ("last_studied", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_notes",
                    models.TextField(
                        blank=True, help_text="AI observations about this subject"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_memories",
                        to="curriculum.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Memory",
                "verbose_name_plural": "Subject Memories",
                "unique_together": {("user", "subject")},
            },
        ),
    ]
