# Generated by Django 5.1.4 on 2026-06-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("did_study", models.BooleanField(default=False)),
                ("hours_completed", models.FloatField(default=0.0)),
                ("chapters_completed", models.JSONField(blank=True, default=list)),
                ("topics_completed", models.JSONField(blank=True, default=list)),
                ("problems_faced", models.TextField(blank=True)),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("great", "😊 Great"),
                            ("good", "🙂 Good"),
                            ("okay", "😐 Okay"),
                            ("bad", "😟 Bad"),
                            ("terrible", "😞 Terrible"),
                        ],
                        default="okay",
                        max_length=10,
                    ),
                ),
                (
                    "productivity_rating",
                    models.IntegerField(default=5, help_text="1-10"),
                ),
                ("notes", models.TextField(blank=True)),
                ("ai_feedback", models.TextField(blank=True)),
                ("ai_suggestions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Daily Check-in",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="RecoveryPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("recovery", "Recovery Plan"),
                            ("catchup", "Catch-up Plan"),
                            ("extra_revision", "Extra Revision Plan"),
                            ("intensive", "Intensive Plan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("tasks", models.JSONField(default=list)),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Why this plan was generated"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Recovery Plan",
                "ordering": ["-created_at"],
            },
        ),
    ]
