# Generated by Django 5.1.4 on 2026-06-15 09:22

import apps.knowledge.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


try:
    is_sqlite = settings.DATABASES.get('default', {}).get('ENGINE', '').endswith('sqlite3')
except Exception:
    is_sqlite = False


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    if not is_sqlite:
        from pgvector.django import VectorExtension
        operations = [
            VectorExtension(),
        ]
    else:
        operations = []

    operations.extend([
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("chunk_index", models.IntegerField(default=0)),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("token_count", models.IntegerField(default=0)),
                (
                    "embedding",
                    apps.knowledge.models.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.chapter",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Chunk",
                "verbose_name_plural": "Document Chunks",
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeCitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conversation_id", models.CharField(max_length=100)),
                ("relevance_score", models.FloatField(default=0.0)),
                ("was_helpful", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="knowledge.documentchunk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Citation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("icai_material", "ICAI Study Material"),
                            ("icai_module", "ICAI Module"),
                            ("icai_publication", "ICAI Publication"),
                            ("icai_notes", "ICAI Notes"),
                            ("rtp", "Revision Test Paper"),
                            ("mtp", "Mock Test Paper"),
                            ("pyq", "Previous Year Question Paper"),
                            ("suggested_answer", "Suggested Answers"),
                            ("teacher_notes", "Teacher Notes"),
                            ("question_bank", "Question Bank"),
                            ("formula_sheet", "Formula Sheet"),
                            ("chapter_notes", "Chapter Notes"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="knowledge/documents/")),
                ("file_type", models.CharField(blank=True, max_length=10)),
                ("file_size", models.IntegerField(default=0, help_text="Bytes")),
                ("page_count", models.IntegerField(default=0)),
                (
                    "year",
                    models.IntegerField(
                        blank=True, help_text="Exam year for PYQ/RTP/MTP", null=True
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        blank=True, help_text="May/November", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("chunking", "Chunking"),
                            ("embedding", "Generating Embeddings"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("chunk_count", models.IntegerField(default=0)),
                (
                    "processing_time",
                    models.FloatField(default=0.0, help_text="Seconds"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=5, help_text="1=highest, 10=lowest for RAG retrieval"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="curriculum.chapter",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="curriculum.subject",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Document",
                "verbose_name_plural": "Knowledge Documents",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="knowledge.knowledgedocument",
            ),
        ),
        migrations.CreateModel(
            name="KnowledgeSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary_type",
                    models.CharField(
                        choices=[
                            ("short_notes", "Short Notes"),
                            ("revision_notes", "Revision Notes"),
                            ("formula_sheet", "Formula Sheet"),
                            ("memory_tricks", "Memory Tricks"),
                            ("chapter_summary", "Chapter Summary"),
                            ("mind_map", "Mind Map"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_summaries",
                        to="curriculum.chapter",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="knowledge.knowledgedocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Summary",
                "verbose_name_plural": "Knowledge Summaries",
            },
        ),
        migrations.CreateModel(
            name="MTPDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("session", models.CharField(max_length=20)),
                ("analysis_json", models.JSONField(blank=True, default=dict)),
                ("trending_topics", models.JSONField(blank=True, default=list)),
                ("importance_scores", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mtp_metadata",
                        to="knowledge.knowledgedocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "MTP Document",
            },
        ),
        migrations.CreateModel(
            name="PreviousYearQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("answer_text", models.TextField(blank=True)),
                ("marks", models.IntegerField(default=1)),
                ("year", models.IntegerField()),
                ("session", models.CharField(blank=True, max_length=20)),
                ("question_type", models.CharField(default="mcq", max_length=20)),
                ("difficulty", models.CharField(default="medium", max_length=10)),
                (
                    "frequency_score",
                    models.FloatField(
                        default=1.0, help_text="How often similar questions appear"
                    ),
                ),
                (
                    "probability_score",
                    models.FloatField(
                        default=0.5, help_text="Probability of appearing in next exam"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pyq_questions",
                        to="curriculum.chapter",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="knowledge.knowledgedocument",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pyq_questions",
                        to="curriculum.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pyq_questions",
                        to="curriculum.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Previous Year Question",
                "ordering": ["-year", "subject"],
            },
        ),
        migrations.CreateModel(
            name="RTPDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("session", models.CharField(max_length=20)),
                (
                    "analysis_json",
                    models.JSONField(
                        blank=True, default=dict, help_text="AI-generated analysis"
                    ),
                ),
                ("trending_topics", models.JSONField(blank=True, default=list)),
                ("importance_scores", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rtp_metadata",
                        to="knowledge.knowledgedocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "RTP Document",
            },
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="knowledge_d_documen_ea33de_idx",
            ),
        ),
    ])
