# Generated by Django 5.1.4 on 2026-06-15 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hours_studied", models.FloatField(default=0.0)),
                ("topics_covered", models.IntegerField(default=0)),
                ("chapters_covered", models.IntegerField(default=0)),
                ("mcqs_attempted", models.IntegerField(default=0)),
                ("mcqs_correct", models.IntegerField(default=0)),
                ("revisions_done", models.IntegerField(default=0)),
                ("tasks_completed", models.IntegerField(default=0)),
                ("tasks_total", models.IntegerField(default=0)),
                ("discipline_score", models.FloatField(default=0.0)),
                ("consistency_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Analytics",
                "verbose_name_plural": "Study Analytics",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
