# Generated by Django 5.1.4 on 2026-06-15 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(default="gemini-2.5-pro", max_length=100),
                ),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=8192)),
                ("memory_token_limit", models.IntegerField(default=3000)),
                ("max_memory_token_limit", models.IntegerField(default=5000)),
                (
                    "embedding_model",
                    models.CharField(default="text-embedding-004", max_length=100),
                ),
                ("embedding_dimensions", models.IntegerField(default=768)),
                ("default_teaching_steps", models.IntegerField(default=9)),
                ("use_stories", models.BooleanField(default=True)),
                ("use_funny_examples", models.BooleanField(default=True)),
                ("use_memory_tricks", models.BooleanField(default=True)),
                (
                    "rag_top_k",
                    models.IntegerField(
                        default=5, help_text="Number of chunks to retrieve"
                    ),
                ),
                (
                    "rag_similarity_threshold",
                    models.FloatField(
                        default=0.7, help_text="Minimum cosine similarity"
                    ),
                ),
                (
                    "rag_priority_icai",
                    models.BooleanField(
                        default=True, help_text="Prioritize ICAI content"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Settings",
                "verbose_name_plural": "AI Settings",
            },
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("teaching", "Teaching"),
                            ("revision", "Revision"),
                            ("mcq_generation", "MCQ Generation"),
                            ("mock_test", "Mock Test"),
                            ("analysis", "Analysis"),
                            ("motivation", "Motivation"),
                            ("explanation", "Explanation"),
                            ("voice", "Voice Interaction"),
                            ("summary", "Summary Generation"),
                            ("checkin", "Daily Check-in"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "template_text",
                    models.TextField(
                        help_text="Use {variable_name} for dynamic content"
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(blank=True, help_text="System context for AI"),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True, default=list, help_text="List of variable names"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prompt Template",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ConversationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("teaching", "Teaching Session"),
                            ("revision", "Revision"),
                            ("voice", "Voice Interaction"),
                            ("mcq", "MCQ Practice"),
                            ("doubt", "Doubt Solving"),
                        ],
                        default="chat",
                        max_length=20,
                    ),
                ),
                ("user_message", models.TextField()),
                ("ai_response", models.TextField()),
                ("memory_tokens_used", models.IntegerField(default=0)),
                ("rag_chunks_used", models.IntegerField(default=0)),
                ("citations", models.JSONField(blank=True, default=list)),
                ("was_helpful", models.BooleanField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.chapter",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation Log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SuccessPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("readiness_score", models.FloatField(default=0.0, help_text="0-100")),
                ("pass_probability", models.FloatField(default=0.0, help_text="0-100")),
                (
                    "risk_score",
                    models.FloatField(
                        default=50.0, help_text="0-100, higher = more risk"
                    ),
                ),
                (
                    "subject_risks",
                    models.JSONField(
                        blank=True, default=dict, help_text="Risk per subject"
                    ),
                ),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("weaknesses", models.JSONField(blank=True, default=list)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("study_hours_factor", models.FloatField(default=0.0)),
                ("consistency_factor", models.FloatField(default=0.0)),
                ("revision_factor", models.FloatField(default=0.0)),
                ("test_score_factor", models.FloatField(default=0.0)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="success_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Success Prediction",
                "ordering": ["-computed_at"],
            },
        ),
    ]
