# Generated by Django 5.1.4 on 2026-06-19 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0001_initial"),
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(default="New Chat", max_length=300)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("teaching", "Teaching Session"),
                            ("revision", "Revision"),
                        ],
                        default="chat",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("message_count", models.IntegerField(default=0)),
                (
                    "last_summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-compressed summary of this session for long-term memory",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.chapter",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="conversationlog",
            name="chat_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="ai_engine.chatsession",
            ),
        ),
    ]
