# Generated by Django 5.1.4 on 2026-06-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0002_chatsession_conversationlog_chat_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="last_summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="AI-compressed summary of this session for long-term memory",
            ),
        ),
    ]
